<?php

namespace ContainerXxENEfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F8KJ3irService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f8KJ3ir' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f8KJ3ir'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adminFacRepository' => ['privates', 'App\\Repository\\AdminFacRepository', 'getAdminFacRepositoryService', true],
        ], [
            'adminFacRepository' => 'App\\Repository\\AdminFacRepository',
        ]);
    }
}
