<?php

namespace ContainerXxENEfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6Z0wS_BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Z0wS.B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Z0wS.B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'etudiantEsprit' => ['privates', '.errored..service_locator.6Z0wS.B.App\\Entity\\EtudiantEsprit', NULL, 'Cannot autowire service ".service_locator.6Z0wS.B": it references class "App\\Entity\\EtudiantEsprit" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'etudiantEsprit' => 'App\\Entity\\EtudiantEsprit',
        ]);
    }
}
