<?php

namespace ContainerXxENEfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2zKsBFvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2zKsBFv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2zKsBFv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.admin_esprit' => ['privates', 'security.event_dispatcher.admin_esprit', 'getSecurity_EventDispatcher_AdminEspritService', false],
            'security.event_dispatcher.admin_fac' => ['privates', 'security.event_dispatcher.admin_fac', 'getSecurity_EventDispatcher_AdminFacService', false],
            'security.event_dispatcher.etudiant_esprit' => ['privates', 'security.event_dispatcher.etudiant_esprit', 'getSecurity_EventDispatcher_EtudiantEspritService', false],
            'security.event_dispatcher.main' => ['privates', 'security.event_dispatcher.main', 'getSecurity_EventDispatcher_MainService', false],
        ], [
            'event_dispatcher' => '?',
            'security.event_dispatcher.admin_esprit' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.admin_fac' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.etudiant_esprit' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.main' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
        ]);
    }
}
