<?php

namespace ContainerXxENEfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LJx2h9EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LJx2h9E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LJx2h9E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adminEsprit' => ['privates', '.errored..service_locator.LJx2h9E.App\\Entity\\AdminEsprit', NULL, 'Cannot autowire service ".service_locator.LJx2h9E": it references class "App\\Entity\\AdminEsprit" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'adminEsprit' => 'App\\Entity\\AdminEsprit',
            'entityManager' => '?',
        ]);
    }
}
