<?php

namespace ContainerXxENEfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VZDCer7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VZDCer7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VZDCer7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'candidature' => ['privates', '.errored..service_locator.VZDCer7.App\\Entity\\Candidature', NULL, 'Cannot autowire service ".service_locator.VZDCer7": it references class "App\\Entity\\Candidature" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'candidature' => 'App\\Entity\\Candidature',
            'entityManager' => '?',
        ]);
    }
}
