<?php

namespace ContainerXxENEfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HCFPcsKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hCFPcsK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hCFPcsK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adminFac' => ['privates', '.errored..service_locator.hCFPcsK.App\\Entity\\AdminFac', NULL, 'Cannot autowire service ".service_locator.hCFPcsK": it references class "App\\Entity\\AdminFac" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'adminFac' => 'App\\Entity\\AdminFac',
            'entityManager' => '?',
        ]);
    }
}
