<?php

namespace ContainerXxENEfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SBqCUEQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sBqCUEQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sBqCUEQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'opportinuteRepository' => ['privates', 'App\\Repository\\OpportinuteRepository', 'getOpportinuteRepositoryService', true],
        ], [
            'opportinuteRepository' => 'App\\Repository\\OpportinuteRepository',
        ]);
    }
}
