<?php

namespace ContainerXxENEfc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminFacService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S6TcVc9.App\Entity\AdminFac' shared service.
     *
     * @return \App\Entity\AdminFac
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.S6TcVc9": it references class "App\\Entity\\AdminFac" but no such service exists.');
    }
}
