<?php

namespace ContainerL0mO7ZK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3Q1YyU2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3Q1YyU2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3Q1YyU2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adminEsprit' => ['privates', '.errored..service_locator.3Q1YyU2.App\\Entity\\AdminEsprit', NULL, 'Cannot autowire service ".service_locator.3Q1YyU2": it references class "App\\Entity\\AdminEsprit" but no such service exists.'],
        ], [
            'adminEsprit' => 'App\\Entity\\AdminEsprit',
        ]);
    }
}
