<?php

namespace ContainerL0mO7ZK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9BSb9WJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9BSb9WJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9BSb9WJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etudiantEspritRepository' => ['privates', 'App\\Repository\\EtudiantEspritRepository', 'getEtudiantEspritRepositoryService', true],
        ], [
            'etudiantEspritRepository' => 'App\\Repository\\EtudiantEspritRepository',
        ]);
    }
}
