<?php

namespace ContainerL0mO7ZK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__O6VrayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..o6Vray' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..o6Vray'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'opportinute' => ['privates', '.errored..service_locator..o6Vray.App\\Entity\\Opportinute', NULL, 'Cannot autowire service ".service_locator..o6Vray": it references class "App\\Entity\\Opportinute" but no such service exists.'],
        ], [
            'opportinute' => 'App\\Entity\\Opportinute',
        ]);
    }
}
