<?php

namespace ContainerL0mO7ZK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PZ02d5lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PZ02d5l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PZ02d5l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etudiantEsprit' => ['privates', '.errored..service_locator.PZ02d5l.App\\Entity\\EtudiantEsprit', NULL, 'Cannot autowire service ".service_locator.PZ02d5l": it references class "App\\Entity\\EtudiantEsprit" but no such service exists.'],
        ], [
            'etudiantEsprit' => 'App\\Entity\\EtudiantEsprit',
        ]);
    }
}
