<?php

namespace ContainerL0mO7ZK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminEsprit2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LJx2h9E.App\Entity\AdminEsprit' shared service.
     *
     * @return \App\Entity\AdminEsprit
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LJx2h9E": it references class "App\\Entity\\AdminEsprit" but no such service exists.');
    }
}
