<?php

namespace ContainerL0mO7ZK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtudiantEspritService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6Z0wS.B.App\Entity\EtudiantEsprit' shared service.
     *
     * @return \App\Entity\EtudiantEsprit
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6Z0wS.B": it references class "App\\Entity\\EtudiantEsprit" but no such service exists.');
    }
}
