<?php

namespace ContainerL0mO7ZK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpportinute2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._knJPf6.App\Entity\Opportinute' shared service.
     *
     * @return \App\Entity\Opportinute
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._knJPf6": it references class "App\\Entity\\Opportinute" but no such service exists.');
    }
}
