<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxENEfc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxENEfc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxENEfc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxENEfc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxENEfc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxENEfc',
    'container.build_id' => 'ac892e46',
    'container.build_time' => 1694531248,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxENEfc');
